//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Tbl_Admin
{
    public short Admin_id { get; set; }
    public string Admin_name { get; set; }
    public string Admin_password { get; set; }
}

public partial class Tbl_Category
{
    public Tbl_Category()
    {
        this.Tbl_Site = new HashSet<Tbl_Site>();
    }

    public short Category_id { get; set; }
    public string Category_name { get; set; }
    public string Category_definition { get; set; }
    public Nullable<byte> Category_total { get; set; }

    public virtual ICollection<Tbl_Site> Tbl_Site { get; set; }
}

public partial class Tbl_Contact
{
    public short Contact_id { get; set; }
    public string Contact_name { get; set; }
    public string Contact_definition { get; set; }
    public string Contact_mail { get; set; }
}

public partial class Tbl_FeedBack
{
    public short FeedBack_id { get; set; }
    public string FeedBack_name { get; set; }
    public string FeedBack_mail { get; set; }
    public Nullable<System.DateTime> FeedBack_date { get; set; }
    public Nullable<bool> FeedBack_status { get; set; }
    public string FeedBack_definition { get; set; }
    public Nullable<short> WebSite_id { get; set; }

    public virtual Tbl_Site Tbl_Site { get; set; }
}

public partial class Tbl_Site
{
    public Tbl_Site()
    {
        this.Tbl_FeedBack = new HashSet<Tbl_FeedBack>();
    }

    public short WebSite_id { get; set; }
    public string WebSite_name { get; set; }
    public string WebSite_url { get; set; }
    public string WebSite_definition { get; set; }
    public Nullable<short> WebSite_category { get; set; }
    public Nullable<bool> WebSite_status { get; set; }
    public string WebSite_suggest { get; set; }

    public virtual Tbl_Category Tbl_Category { get; set; }
    public virtual ICollection<Tbl_FeedBack> Tbl_FeedBack { get; set; }
}
