//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DB_PageRouterEntities2 : DbContext
{
    public DB_PageRouterEntities2()
        : base("name=DB_PageRouterEntities2")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Tbl_Admin> Tbl_Admin { get; set; }
    public DbSet<Tbl_Category> Tbl_Category { get; set; }
    public DbSet<Tbl_Contact> Tbl_Contact { get; set; }
    public DbSet<Tbl_FeedBack> Tbl_FeedBack { get; set; }
    public DbSet<Tbl_Site> Tbl_Site { get; set; }
}
